import { PATHS } from "../constants.js";
import type { PlannedFile } from "../core/types.js";
import { estimateTokens } from "../core/token-estimator.js";
import type { GenContext } from "./context.js";

function pf(path: string, contents: string): PlannedFile {
  return { path, contents, tokens: estimateTokens(contents), host: "cursor" };
}

/**
 * Cursor mirror: `.cursor/rules/*.mdc` (glob-scoped) + `AGENTS.md` (shared
 * convention). Generated from the same context as the Claude surface — one
 * source, two faces (PRD §4). `mdc` files carry frontmatter with globs.
 */
function mdc(description: string, globs: string, body: string): string {
  return `---\ndescription: ${description}\nglobs: ${globs}\nalwaysApply: false\n---\n\n${body}\n`;
}

export function generateCursor(ctx: GenContext): PlannedFile[] {
  const files: PlannedFile[] = [];

  files.push(
    pf(
      `${PATHS.cursorRules}/agent-stack-core.mdc`,
      mdc(
        "agent-stack core conventions for this repo",
        "**/*",
        `# ${ctx.repoName} — core conventions\n\n- Profile: \`${ctx.profileName}\`. Graph: \`${ctx.graph}\`. Compression: \`${ctx.compression}\`.\n- Prefer graph queries and targeted reads over loading whole directories.\n- Keep responses terse to minimize token cost.\n- See \`AGENTS.md\` for the shared convention shared with Claude Code.`,
      ),
    ),
  );

  files.push(
    pf(
      `${PATHS.cursorRules}/agent-stack-${ctx.language.toLowerCase().replace(/[^a-z]/g, "") || "code"}.mdc`,
      mdc(
        `${ctx.language} conventions`,
        ctx.language === "TypeScript" ? "**/*.{ts,tsx}" : "**/*",
        `# ${ctx.language} rules\n\n- Framework: ${ctx.framework}.\n- Match existing style; do not reformat unrelated code.\n- Run the project's own test/lint before claiming done.`,
      ),
    ),
  );

  files.push(
    pf(
      `${PATHS.cursorRules}/agent-stack-architecture.mdc`,
      mdc("Architecture map reference", "**/*", `# Architecture\n\nSee \`ARCHITECTURE_MAP.md\` for structure and \`COMMON_MISTAKES.md\` for known traps.`),
    ),
  );

  files.push(
    pf(
      `${PATHS.cursorRules}/agent-stack-measure.mdc`,
      mdc("How savings are measured", "**/*", `# Measurement\n\nToken usage is tracked via \`ccusage\`. Run \`npx @drmahdikazempour/agent-stack measure --since 7d\` to see savings.`),
    ),
  );

  // AGENTS.md — the shared convention both hosts read.
  files.push(
    pf(
      PATHS.agentsMd,
      `# AGENTS.md

Shared agent convention for **${ctx.repoName}** (read by Claude Code and Cursor).

- **Profile:** \`${ctx.profileName}\`
- **Code graph:** \`${ctx.graph}\` — query before reading files wholesale.
- **Shell compression:** \`${ctx.compression}\` — large output is compressed automatically.
- **Measurement:** \`ccusage\`.

## Working agreement
- Prefer the graph and targeted reads over loading whole directories.
- Keep responses terse; the user values low token cost.
- Match existing code style; never reformat unrelated code.
- Run the project's own test/lint commands before claiming done.

_Generated by agent-stack. Edit \`CLAUDE.md\` and run \`npx @drmahdikazempour/agent-stack sync\` to regenerate this mirror._
`,
    ),
  );

  return files;
}
