import fs from "node:fs";
import path from "node:path";
import { PATHS } from "../constants.js";
import { color, run, sym, readFileSafe } from "../core/util.js";

const HANDOFF_FILE = path.posix.join(PATHS.stateDir, "handoff.md");

/** Continuity files (PRD §6 handoff write|resume). Built-in template, no external dep. */
export function runHandoff(cwd: string, mode: "write" | "resume"): { ok: boolean } {
  if (mode === "resume") return resume(cwd);
  return write(cwd);
}

function write(cwd: string): { ok: boolean } {
  const branch = run("git", ["rev-parse", "--abbrev-ref", "HEAD"], { cwd });
  const status = run("git", ["status", "--short"], { cwd });
  const log = run("git", ["log", "-5", "--oneline"], { cwd });

  const contents = `# Handoff — ${new Date().toISOString()}

## Git state
- Branch: ${branch.ok ? branch.stdout.trim() : "(not a git repo)"}
- Uncommitted changes:
\`\`\`
${status.ok ? status.stdout.trim() || "(clean)" : "(unknown)"}
\`\`\`
- Recent commits:
\`\`\`
${log.ok ? log.stdout.trim() : "(none)"}
\`\`\`

## Current task
_(describe what you are working on)_

## Decisions made
_(key choices and why)_

## Open threads / next steps
- [ ] _(next step)_

_Generated by agent-stack handoff. Edit freely; \`handoff resume\` prints this back._
`;

  const full = path.join(cwd, HANDOFF_FILE);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, contents, "utf8");
  console.log(`${sym.ok} Handoff written → ${HANDOFF_FILE}`);
  return { ok: true };
}

function resume(cwd: string): { ok: boolean } {
  const contents = readFileSafe(path.join(cwd, HANDOFF_FILE));
  if (!contents) {
    console.log(`${sym.warn} No handoff found. Run \`agent-stack handoff write\` first.`);
    return { ok: false };
  }
  console.log(color.dim(`── ${HANDOFF_FILE} ──`));
  console.log(contents);
  return { ok: true };
}
