import fs from "node:fs";
import path from "node:path";

/**
 * Built-in, dependency-free code map. Walks the repo and extracts top-level
 * symbols per source file via language-aware regexes, then writes a compact
 * `.agent-stack/graph.md`. The agent greps this one small file to locate a
 * symbol instead of opening many files — that's the real token saving, and it
 * works without installing any (unrelated) "codegraph" npm package.
 */

const SKIP_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  "coverage",
  ".agent-stack",
  "vendor",
  "__pycache__",
  ".venv",
  "target",
]);

interface Extractor {
  ext: RegExp;
  patterns: RegExp[];
}

const EXTRACTORS: Extractor[] = [
  {
    ext: /\.(ts|tsx|js|jsx|mjs|cjs)$/,
    patterns: [
      /^export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/gm,
      /^export\s+(?:abstract\s+)?class\s+([A-Za-z0-9_]+)/gm,
      /^export\s+const\s+([A-Za-z0-9_]+)/gm,
      /^export\s+(?:type|interface|enum)\s+([A-Za-z0-9_]+)/gm,
      /^export\s+default\s+(?:function|class)\s+([A-Za-z0-9_]+)/gm,
    ],
  },
  {
    ext: /\.py$/,
    patterns: [/^def\s+([A-Za-z0-9_]+)/gm, /^class\s+([A-Za-z0-9_]+)/gm],
  },
  {
    ext: /\.go$/,
    patterns: [/^func\s+(?:\([^)]*\)\s*)?([A-Za-z0-9_]+)/gm, /^type\s+([A-Za-z0-9_]+)/gm],
  },
  {
    ext: /\.rs$/,
    patterns: [/^pub\s+(?:async\s+)?fn\s+([A-Za-z0-9_]+)/gm, /^pub\s+(?:struct|enum|trait)\s+([A-Za-z0-9_]+)/gm],
  },
];

function extractorFor(file: string): Extractor | null {
  return EXTRACTORS.find((e) => e.ext.test(file)) ?? null;
}

interface FileEntry {
  path: string;
  symbols: string[];
}

export interface GraphResult {
  entries: FileEntry[];
  fileCount: number;
  symbolCount: number;
}

export function buildGraph(root: string, cap = 4000): GraphResult {
  const entries: FileEntry[] = [];
  let symbolCount = 0;
  let seen = 0;
  const stack = [root];

  while (stack.length && seen < cap) {
    const dir = stack.pop()!;
    let dirents: fs.Dirent[];
    try {
      dirents = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const ent of dirents) {
      if (seen >= cap) break;
      if (ent.isDirectory()) {
        if (!SKIP_DIRS.has(ent.name) && !ent.name.startsWith(".agent-stack")) {
          stack.push(path.join(dir, ent.name));
        }
        continue;
      }
      if (!ent.isFile()) continue;
      const ex = extractorFor(ent.name);
      if (!ex) continue;
      seen++;
      const full = path.join(dir, ent.name);
      let src: string;
      try {
        if (fs.statSync(full).size > 2_000_000) continue; // skip huge files
        src = fs.readFileSync(full, "utf8");
      } catch {
        continue;
      }
      const symbols = new Set<string>();
      for (const pat of ex.patterns) {
        pat.lastIndex = 0;
        let m: RegExpExecArray | null;
        while ((m = pat.exec(src)) !== null) {
          if (m[1]) symbols.add(m[1]);
        }
      }
      if (symbols.size === 0) continue;
      const rel = path.relative(root, full);
      const syms = [...symbols].sort();
      entries.push({ path: rel, symbols: syms });
      symbolCount += syms.length;
    }
  }

  entries.sort((a, b) => a.path.localeCompare(b.path));
  return { entries, fileCount: entries.length, symbolCount };
}

export function renderGraphMarkdown(result: GraphResult): string {
  const lines: string[] = [
    "# Code map",
    "",
    `_Generated by agent-stack. ${result.fileCount} files, ${result.symbolCount} top-level symbols. Grep this file to find where a symbol is defined before opening source — it saves reading whole files._`,
    "",
  ];
  for (const e of result.entries) {
    lines.push(`- \`${e.path}\`: ${e.symbols.join(", ")}`);
  }
  return lines.join("\n") + "\n";
}
